
#define MEM_OFFSET_TYPE 0
#define MEM_OFFSET_CFG_RAINBOW_SPEED 1
#define MEM_OFFSET_CFG_RAINBOW_OFFSET_X 2
#define MEM_OFFSET_CFG_RAINBOW_OFFSET_Y 3
#define MEM_OFFSET_CFG_POINTS_SLOW 4
#define MEM_OFFSET_CFG_RANDOM_SLOW 5