
#define MEM_OFFSET_TYPE 0
#define MEM_OFFSET_CFG_RAINBOW_SPEED 1
#define MEM_OFFSET_CFG_RAINBOW_OFFSET_X 2
#define MEM_OFFSET_CFG_RAINBOW_OFFSET_Y 3
#define MEM_OFFSET_CFG_POINTS_SLOW 4
#define MEM_OFFSET_CFG_RANDOM_SLOW 5
#define MEM_OFFSET_CFG_SINGLE_COLOR_HUE 6
#define MEM_OFFSET_CFG_SINGLE_COLOR_SATURATION 7

#define MEM_OFFSET_CFG_ALL_BRIGHTNESS 8

#define MEM_OFFSET_CFG_TEXT_START 9
#define MEM_OFFSET_CFG_TEXT_END 209

#define MEM_OFFSET_CFG_TEXT_HUE_TEXT 210
#define MEM_OFFSET_CFG_TEXT_SATURATION_TEXT 211
#define MEM_OFFSET_CFG_TEXT_HUE_BG 212
#define MEM_OFFSET_CFG_TEXT_SATURATION_BG 213
#define MEM_OFFSET_CFG_TEXT_SLOW 214

